# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - formulaonewebapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://formulaoneapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ff29511ed0cc41f4bfcd305ffd57acf6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_67732f84467b457a8230d6b98f300f20 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: formulaoneapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ff29511ed0cc41f4bfcd305ffd57acf6 }}/k8sdriverapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'formulaonewebapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_965230c5d5c347f5a2b5e6e57a0b1cb9 }}
        images: 'formulaoneapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ff29511ed0cc41f4bfcd305ffd57acf6 }}/k8sdriverapi:${{ github.sha }}'